### ISSUE TITLE
US-7: Auto generate SVG and piecelist

### ISSUE THREAD

**Issue by Legolai** [Legolai/CarportEksamensProject#10]
## **Is needed**

- #11  
- #7   
- #9 

## Tasks
- [x] Auto generate a SVG out of an inquiry
- [x] Auto generate a piecelist out of an inquiry
- [x] The employee or admin can make changes to both the SVG or the piecelist.

### Description
A client can after accessing an inquiry, both view a SVG and piecelist and he can also make changes to both of them.
