### ISSUE TITLE
Inquiry mapper

### ISSUE THREAD

**Issue by Legolai** [Legolai/CarportEksamensProject#13]
## Is needed

- #11 

## Tasks
- [x] Inquiry (Class)
- [x] Inquiry mapper (Class)
- [x] Get all (Method)
- [x] Find by user id (Method)
