### ISSUE TITLE
US-6: Inquiries page

### ISSUE THREAD

**Issue by Legolai** [Legolai/CarportEksamensProject#9]
## **Is needed**

- #11  
- #7   

## Tasks
- [x] Access a page with inquiries (employee and admin role only)
- [x] Able to access individual inquiries
- [x] Able to change the status of an inquiry
- [x] Able to answer the customer that made the inquiry

### Description
A client who is an employee or admin, can access an inquiries page, that displays all inquiries. The client can then access individual inquiries and change their status or answer the customer.
